"""Add Page and PageRender models

Revision ID: 14f3d8e26321
Revises: a6f7220bf94d
Create Date: 2025-12-05 19:11:49.180012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f3d8e26321'
down_revision = 'a6f7220bf94d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.String(length=300), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.create_index('idx_page_slug', ['slug'], unique=False)

    op.create_table('page_render',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('rendered_html', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_render')
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_index('idx_page_slug')

    op.drop_table('page')
    # ### end Alembic commands ###
