"""Phase 25-30: Add backup, deployment, security, MFA, privacy models

Revision ID: 2faf67ed8ad3
Revises: 4b60e9e748da
Create Date: 2025-12-07 01:26:48.923650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2faf67ed8ad3'
down_revision = '4b60e9e748da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('backup_type', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('storage_location', sa.String(length=50), nullable=True),
    sa.Column('encryption_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backup_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('encrypted', sa.Boolean(), nullable=True),
    sa.Column('storage_location', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['backup_schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup', schema=None) as batch_op:
        batch_op.create_index('idx_backup_started', ['started_at'], unique=False)
        batch_op.create_index('idx_backup_type_status', ['backup_type', 'status'], unique=False)

    op.create_table('consent_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('consent_source', sa.String(length=50), nullable=True),
    sa.Column('policy_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_record', schema=None) as batch_op:
        batch_op.create_index('idx_consent_session', ['session_id'], unique=False)
        batch_op.create_index('idx_consent_user_type', ['user_id', 'consent_type'], unique=False)

    op.create_table('data_export_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_format', sa.String(length=10), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_export_request', schema=None) as batch_op:
        batch_op.create_index('idx_export_user_status', ['user_id', 'status'], unique=False)

    op.create_table('deployment_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('deployed_by_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rollback_version', sa.String(length=50), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('migration_ran', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['deployed_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployment_log', schema=None) as batch_op:
        batch_op.create_index('idx_deployment_env_status', ['environment', 'status'], unique=False)
        batch_op.create_index('idx_deployment_started', ['started_at'], unique=False)

    op.create_table('feature_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('rollout_percentage', sa.Integer(), nullable=True),
    sa.Column('user_whitelist', sa.JSON(), nullable=True),
    sa.Column('user_blacklist', sa.JSON(), nullable=True),
    sa.Column('segment_ids', sa.JSON(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('feature_flag', schema=None) as batch_op:
        batch_op.create_index('idx_feature_flag_name', ['name'], unique=False)

    op.create_table('ip_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('blocked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('blocked_by_id', sa.Integer(), nullable=True),
    sa.Column('auto_blocked', sa.Boolean(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ip_blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ip_blacklist_ip_address'), ['ip_address'], unique=True)

    op.create_table('login_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempt', schema=None) as batch_op:
        batch_op.create_index('idx_login_attempt_created', ['created_at'], unique=False)
        batch_op.create_index('idx_login_attempt_email_ip', ['email', 'ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempt_email'), ['email'], unique=False)

    op.create_table('mfa_challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_type', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mfa_challenge', schema=None) as batch_op:
        batch_op.create_index('idx_mfa_challenge_user', ['user_id', 'created_at'], unique=False)

    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_history', schema=None) as batch_op:
        batch_op.create_index('idx_password_history_user', ['user_id', 'created_at'], unique=False)

    op.create_table('retention_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_executed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_interval_hours', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_mfa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mfa_type', sa.String(length=20), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=True),
    sa.Column('backup_codes_encrypted', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_mfa', schema=None) as batch_op:
        batch_op.create_index('idx_user_mfa_user_type', ['user_id', 'mfa_type'], unique=False)

    op.create_table('data_retention_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_deleted', sa.Integer(), nullable=True),
    sa.Column('records_anonymized', sa.Integer(), nullable=True),
    sa.Column('records_archived', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['retention_policy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_retention_log', schema=None) as batch_op:
        batch_op.create_index('idx_retention_log_policy', ['policy_id', 'executed_at'], unique=False)

    op.create_table('post_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_view', schema=None) as batch_op:
        batch_op.create_index('idx_postview_post_viewed', ['post_id', 'viewed_at'], unique=False)
        batch_op.create_index('idx_postview_session', ['session_id'], unique=False)

    op.create_table('webhook_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhook.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('webhook_delivery', schema=None) as batch_op:
        batch_op.create_index('idx_webhook_delivery_idempotency', ['idempotency_key'], unique=False)
        batch_op.create_index('idx_webhook_delivery_retry', ['next_retry_at'], unique=False)
        batch_op.create_index('idx_webhook_delivery_status', ['webhook_id', 'status_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_delivery', schema=None) as batch_op:
        batch_op.drop_index('idx_webhook_delivery_status')
        batch_op.drop_index('idx_webhook_delivery_retry')
        batch_op.drop_index('idx_webhook_delivery_idempotency')

    op.drop_table('webhook_delivery')
    with op.batch_alter_table('post_view', schema=None) as batch_op:
        batch_op.drop_index('idx_postview_session')
        batch_op.drop_index('idx_postview_post_viewed')

    op.drop_table('post_view')
    with op.batch_alter_table('data_retention_log', schema=None) as batch_op:
        batch_op.drop_index('idx_retention_log_policy')

    op.drop_table('data_retention_log')
    with op.batch_alter_table('user_mfa', schema=None) as batch_op:
        batch_op.drop_index('idx_user_mfa_user_type')

    op.drop_table('user_mfa')
    op.drop_table('retention_policy')
    with op.batch_alter_table('password_history', schema=None) as batch_op:
        batch_op.drop_index('idx_password_history_user')

    op.drop_table('password_history')
    with op.batch_alter_table('mfa_challenge', schema=None) as batch_op:
        batch_op.drop_index('idx_mfa_challenge_user')

    op.drop_table('mfa_challenge')
    with op.batch_alter_table('login_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempt_email'))
        batch_op.drop_index('idx_login_attempt_email_ip')
        batch_op.drop_index('idx_login_attempt_created')

    op.drop_table('login_attempt')
    with op.batch_alter_table('ip_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ip_blacklist_ip_address'))

    op.drop_table('ip_blacklist')
    with op.batch_alter_table('feature_flag', schema=None) as batch_op:
        batch_op.drop_index('idx_feature_flag_name')

    op.drop_table('feature_flag')
    with op.batch_alter_table('deployment_log', schema=None) as batch_op:
        batch_op.drop_index('idx_deployment_started')
        batch_op.drop_index('idx_deployment_env_status')

    op.drop_table('deployment_log')
    with op.batch_alter_table('data_export_request', schema=None) as batch_op:
        batch_op.drop_index('idx_export_user_status')

    op.drop_table('data_export_request')
    with op.batch_alter_table('consent_record', schema=None) as batch_op:
        batch_op.drop_index('idx_consent_user_type')
        batch_op.drop_index('idx_consent_session')

    op.drop_table('consent_record')
    with op.batch_alter_table('backup', schema=None) as batch_op:
        batch_op.drop_index('idx_backup_type_status')
        batch_op.drop_index('idx_backup_started')

    op.drop_table('backup')
    op.drop_table('backup_schedule')
    # ### end Alembic commands ###
