"""Phase 22: Registration and UX Hardening

Revision ID: 4b60e9e748da
Revises: b5e0970377f3
Create Date: 2025-12-06 23:08:14.371377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b60e9e748da'
down_revision = 'b5e0970377f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=50), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'step_name', name='uq_onboarding_step')
    )
    with op.batch_alter_table('onboarding_step', schema=None) as batch_op:
        batch_op.create_index('idx_onboarding_user', ['user_id'], unique=False)

    op.create_table('saved_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', 'item_id', name='uq_saved_item')
    )
    with op.batch_alter_table('saved_item', schema=None) as batch_op:
        batch_op.create_index('idx_saved_user_type', ['user_id', 'item_type'], unique=False)

    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_type', sa.String(length=50), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.create_index('idx_activity_type', ['activity_type'], unique=False)
        batch_op.create_index('idx_activity_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_marketing', sa.Boolean(), nullable=True),
    sa.Column('email_order_updates', sa.Boolean(), nullable=True),
    sa.Column('email_appointment_reminders', sa.Boolean(), nullable=True),
    sa.Column('email_digest_weekly', sa.Boolean(), nullable=True),
    sa.Column('email_newsletter', sa.Boolean(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('show_activity_status', sa.Boolean(), nullable=True),
    sa.Column('show_profile_publicly', sa.Boolean(), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('data_export_requested_at', sa.DateTime(), nullable=True),
    sa.Column('data_export_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('oauth_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_verification_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('profile_completion_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_activity_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('timezone')
        batch_op.drop_column('last_activity_at')
        batch_op.drop_column('onboarding_completed_at')
        batch_op.drop_column('onboarding_completed')
        batch_op.drop_column('profile_completion_score')
        batch_op.drop_column('email_verification_sent_at')
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('oauth_id')
        batch_op.drop_column('oauth_provider')

    op.drop_table('user_preference')
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.drop_index('idx_activity_user_created')
        batch_op.drop_index('idx_activity_type')

    op.drop_table('user_activity')
    with op.batch_alter_table('saved_item', schema=None) as batch_op:
        batch_op.drop_index('idx_saved_user_type')

    op.drop_table('saved_item')
    with op.batch_alter_table('onboarding_step', schema=None) as batch_op:
        batch_op.drop_index('idx_onboarding_user')

    op.drop_table('onboarding_step')
    # ### end Alembic commands ###
