"""Phase 2: Calendar and Scheduling models

Revision ID: 90fee8e7a667
Revises: c38177742b22
Create Date: 2025-12-05 22:15:33.577140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fee8e7a667'
down_revision = 'c38177742b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimator_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estimator_id'], ['estimator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.create_index('idx_availability_estimator_day', ['estimator_id', 'day_of_week'], unique=False)

    op.create_table('availability_exception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimator_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('custom_start_time', sa.Time(), nullable=True),
    sa.Column('custom_end_time', sa.Time(), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estimator_id'], ['estimator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability_exception', schema=None) as batch_op:
        batch_op.create_index('idx_exception_estimator_date', ['estimator_id', 'date'], unique=False)

    op.create_table('reschedule_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('proposed_datetime', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reschedule_request', schema=None) as batch_op:
        batch_op.create_index('idx_reschedule_status', ['status'], unique=False)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('checked_in_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('checked_out_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurring_parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'appointment', ['recurring_parent_id'], ['id'])

    with op.batch_alter_table('estimator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_subscription', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('duration_minutes')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('stripe_price_id')
        batch_op.drop_column('is_subscription')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('estimator', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recurring_parent_id')
        batch_op.drop_column('is_recurring')
        batch_op.drop_column('checked_out_at')
        batch_op.drop_column('checked_in_at')
        batch_op.drop_column('staff_notes')

    with op.batch_alter_table('reschedule_request', schema=None) as batch_op:
        batch_op.drop_index('idx_reschedule_status')

    op.drop_table('reschedule_request')
    with op.batch_alter_table('availability_exception', schema=None) as batch_op:
        batch_op.drop_index('idx_exception_estimator_date')

    op.drop_table('availability_exception')
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_index('idx_availability_estimator_day')

    op.drop_table('availability')
    # ### end Alembic commands ###
