"""Phase 17 Scheduling Retry

Revision ID: b5e0970377f3
Revises: 1584c982415c
Create Date: 2025-12-06 13:24:28.036565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e0970377f3'
down_revision = '1584c982415c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('staff_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('checked_in_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('checked_out_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurring_parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('appointment_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_attendees', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_attendees', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('intake_form_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('checked_in_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('confirmation_sent_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_appointment_type', 'appointment_type', ['appointment_type_id'], ['id'])
        batch_op.create_foreign_key('fk_user_location', 'location', ['location_id'], ['id'])
        batch_op.create_foreign_key('fk_gen_appointment_recurring_parent_id', 'appointment', ['recurring_parent_id'], ['id'])

    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_direct', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.create_index('idx_channel_archived', ['is_archived'], unique=False)
        batch_op.create_index('idx_channel_type', ['type'], unique=False)
        batch_op.create_foreign_key('fk_gen_user_created_by_id', 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('contact_form_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('custom_fields', sa.JSON(), nullable=True))
        batch_op.create_foreign_key('fk_user_location', 'location', ['location_id'], ['id'])
        batch_op.create_foreign_key('fk_gen_user_assigned_to_id', 'user', ['assigned_to_id'], ['id'])

    with op.batch_alter_table('encrypted_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('requires_signature', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('signed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('signed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('mimetype', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=True))
        batch_op.create_index('idx_doc_expiry', ['expires_at'], unique=False)
        batch_op.create_index('idx_doc_user_category', ['user_id', 'category'], unique=False)
        batch_op.create_foreign_key('fk_gen_user_signed_by_id', 'user', ['signed_by_id'], ['id'])

    with op.batch_alter_table('estimator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_gen_user_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('admin_notes', sa.Text(), nullable=True))
        batch_op.create_index('idx_leave_dates', ['start_date', 'end_date'], unique=False)
        batch_op.create_index('idx_leave_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_foreign_key('fk_gen_user_approved_by_id', 'user', ['approved_by_id'], ['id'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_message_channel_created', ['channel_id', 'created_at'], unique=False)
        batch_op.create_foreign_key('fk_gen_message_parent_id', 'message', ['parent_id'], ['id'])

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('canonical_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('schema_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_page_status', ['status'], unique=False)
        batch_op.create_foreign_key('fk_gen_user_author_id', 'user', ['author_id'], ['id'])

    with op.batch_alter_table('page_view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('load_time_ms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('utm_source', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('utm_medium', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('utm_campaign', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('utm_term', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('utm_content', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('device_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('browser', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('os', sa.String(length=50), nullable=True))
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.create_index('idx_pageview_session', ['session_id'], unique=False)
        batch_op.create_index('idx_pageview_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('idx_pageview_url', ['url'], unique=False)
        batch_op.create_index('idx_pageview_utm', ['utm_source', 'utm_medium', 'utm_campaign'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_view_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_view_timestamp'), ['timestamp'], unique=False)
        batch_op.create_foreign_key('fk_gen_user_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blog_category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('series_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('series_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('publish_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('read_time_minutes', sa.Integer(), nullable=True))
        batch_op.create_index('idx_post_publish_at', ['publish_at'], unique=False)
        batch_op.create_foreign_key('fk_post_series', 'post_series', ['series_id'], ['id'])
        batch_op.create_foreign_key('fk_post_category', 'blog_category', ['blog_category_id'], ['id'])

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_retries', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('next_retry_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))
        batch_op.create_index('idx_task_next_retry', ['next_retry_at'], unique=False)
        batch_op.create_index('idx_task_status_priority', ['status', 'priority'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reports_to_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile_photo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_location', 'location', ['location_id'], ['id'])
        batch_op.create_foreign_key('fk_user_media', 'media', ['profile_photo_id'], ['id'])
        batch_op.create_foreign_key('fk_user_reports', 'user', ['reports_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('profile_photo_id')
        batch_op.drop_column('department')
        batch_op.drop_column('job_title')
        batch_op.drop_column('reports_to_id')
        batch_op.drop_column('location_id')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index('idx_task_status_priority')
        batch_op.drop_index('idx_task_next_retry')
        batch_op.drop_column('priority')
        batch_op.drop_column('next_retry_at')
        batch_op.drop_column('max_retries')
        batch_op.drop_column('retry_count')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('duration_minutes')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_post_publish_at')
        batch_op.drop_column('read_time_minutes')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('publish_at')
        batch_op.drop_column('series_order')
        batch_op.drop_column('series_id')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('blog_category_id')

    with op.batch_alter_table('page_view', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_page_view_timestamp'))
        batch_op.drop_index(batch_op.f('ix_page_view_session_id'))
        batch_op.drop_index('idx_pageview_utm')
        batch_op.drop_index('idx_pageview_url')
        batch_op.drop_index('idx_pageview_timestamp')
        batch_op.drop_index('idx_pageview_session')
        batch_op.alter_column('user_agent',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('os')
        batch_op.drop_column('browser')
        batch_op.drop_column('device_type')
        batch_op.drop_column('utm_content')
        batch_op.drop_column('utm_term')
        batch_op.drop_column('utm_campaign')
        batch_op.drop_column('utm_medium')
        batch_op.drop_column('utm_source')
        batch_op.drop_column('load_time_ms')
        batch_op.drop_column('user_id')
        batch_op.drop_column('session_id')

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_page_status')
        batch_op.drop_column('author_id')
        batch_op.drop_column('schema_type')
        batch_op.drop_column('canonical_url')
        batch_op.drop_column('status')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_message_channel_created')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_leave_user_status')
        batch_op.drop_index('idx_leave_dates')
        batch_op.drop_column('admin_notes')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('leave_type')

    with op.batch_alter_table('estimator', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('encrypted_document', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_doc_user_category')
        batch_op.drop_index('idx_doc_expiry')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('mimetype')
        batch_op.drop_column('signed_at')
        batch_op.drop_column('signed_by_id')
        batch_op.drop_column('requires_signature')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('category')

    with op.batch_alter_table('contact_form_submission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('custom_fields')
        batch_op.drop_column('assigned_to_id')
        batch_op.drop_column('source')
        batch_op.drop_column('location_id')

    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_channel_type')
        batch_op.drop_index('idx_channel_archived')
        batch_op.drop_column('description')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('is_direct')
        batch_op.drop_column('is_archived')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('confirmation_sent_at')
        batch_op.drop_column('checked_in_method')
        batch_op.drop_column('intake_form_data')
        batch_op.drop_column('max_attendees')
        batch_op.drop_column('current_attendees')
        batch_op.drop_column('appointment_type_id')
        batch_op.drop_column('recurring_parent_id')
        batch_op.drop_column('is_recurring')
        batch_op.drop_column('checked_out_at')
        batch_op.drop_column('checked_in_at')
        batch_op.drop_column('staff_notes')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###
