"""Phase 1 complete

Revision ID: c38177742b22
Revises: 5805a4628029
Create Date: 2025-12-05 22:01:18.784731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38177742b22'
down_revision = '5805a4628029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_subscription', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('stripe_price_id')
        batch_op.drop_column('is_subscription')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
